
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 05 21:38:56 CEST 2014
//----------------------------------------------------

package asint.cup;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int AND = 16;
  public static final int LT = 12;
  public static final int INT = 22;
  public static final int OR = 17;
  public static final int NOT = 9;
  public static final int IDEN = 2;
  public static final int TRUE = 25;
  public static final int GT = 14;
  public static final int SUB = 19;
  public static final int PCI = 5;
  public static final int ASIGNACION = 6;
  public static final int EOF = 0;
  public static final int DIV_SEC = 8;
  public static final int DIV = 21;
  public static final int ADD = 18;
  public static final int PAP = 4;
  public static final int FALSE = 24;
  public static final int error = 1;
  public static final int LET = 13;
  public static final int EQ = 10;
  public static final int BOOL = 23;
  public static final int PUNTO_COMA = 7;
  public static final int MUL = 20;
  public static final int NEQ = 11;
  public static final int ENT = 3;
  public static final int GET = 15;
}

